### ISSUE TITLE
Deleting forum categories hides all related topics

### ISSUE THREAD

**Issue by kdoshere** [e621ng/e621ng#159]
Hi
Theres an issue that will arise when we create an "A" category, use it for a bit and then delete it, all the topics that were associated with that category will be reassigned to category 0.

And then those will no longer appear in thee view(all) and when trying to see them it will result in:

undefined method `can_view' for nil:NilClass

app/models/forum_topic.rb:148:in `visible?'

app/controllers/forum_posts_controller.rb:86:in `check_min_level'

Maybe instead of assigning them to category 0 we could have the option to assign them to another existing category?

Also the hide/unhide options in the posts will throw a :hide! exception

app/models/forum_post.rb:209:214

Seems like the name change was overlooked.

**Comment by kiranoot** [comment]
In the case of there being no categories it still doesn't work, which is unfortunate. The entire concept of deleting categories hasn't been used in practice in the production code base. It would probably make more sense to entirely remove it from the UI and include only a utility method on the model to transfer items from one category to another based on id, as it's really a coder only action to begin with.

**Comment by kiranoot** [comment]
Thanks for the heads up on the bad method references on hiding posts. It does look like I missed those when they were renamed.

**Comment by mm12** [comment]
> Also the hide/unhide options in the posts will throw a :hide! exception
> 
> app/models/forum_post.rb:209:214
> 
> Seems like the name change was overlooked.

This one is fixed in https://github.com/e621ng/e621ng/commit/e649764c9ea025e4e3cdbf20656df16c3fc4ac2e

As for the other issue, we don't really deal with deleting forum categories, well, ever... as Kira pointed out. So it really is a low priority issue. And since you can't actual delete it via the UI, I'm unsure if a fix is actually needed.

~~I also deleted a category and was unable to replicate the issue~~
Well, nevermind, I figured out how to replicate it.

**Comment by mm12** [comment]
Still low priority -- Can only be done though the Rails Console and isn't used in prod.

### Steps to repro: 
1. Create a category on `/forum_categories` - give it a high `order` number to make things easier.
2. Create a topic on the category
3. Delete the category. No way to do it in the UI, but you can execute something like `ForumCategory.last.delete` in the rails console. 

### Expected behavior
Forum topic is migrated to default category. Forum topic remains viewable in the default category and `all` view.. 

### Actual behavior
Forum topic is not listed in the `all` view. Forum topic is not migrated. Manually navigating to it results in `undefined method `can_view' for nil (NoMethodError)` originating from https://github.com/e621ng/e621ng/blob/14f08a80dd38f9161f1ca560afdeab5036c23fee/app/models/forum_topic.rb#L146-L149

### Notes: 
- Deleting does not call `reassign_topics` - only on destroy
- Running `reassign_topics` manually does not fix the issue. It appears that it does not properly update the model, only the id.
  -  `category_name` => `(Unknown)`
  - `category_valid` => aborts
